site_name: OpenUI Documentation
site_description: The OpenAPI for Large Action Models (LAM)
site_author: aigamer-dev
site_url: https://aigamer-dev.github.io/openui/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tooltips

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aigamer-dev/openui
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aigamer_dev

nav:
  - Home: index.md
  - Learn:
      - OpenUI CLI: learn/cli.md
      - Benchmarks: learn/benchmarks.md
  - The Standard:
      - Protocol Overview: standards/protocol.md
      - Agent-UI Schema: standards/agent-ui.md
  - Usage: usage.md
  - Community:
      - Contributing: CONTRIBUTING.md
      - Development Guide: DEVELOPMENT.md
